name: Deploy Core Automation Service

on:
  push:
    branches: [main]
    paths:
      - "core_automation/**"
      - ".github/workflows/core_automation.release.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to - IE: dev / prod"
        required: true
        default: "prod"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: ./core_automation

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: google-github-actions/release-please-action@v3
          id: release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release-type: python
            path: core_automation
            monorepo-tags: true
            package-name: core_automation
            tag-separator: '@'
