name: Deploy Main Cli

on:
  push:
    branches: [main]
    paths:
      - "core_automation/**"
      - "main_cli/**"
      - ".github/workflows/main_cli.release.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to - IE: dev / prod"
        required: true
        default: "dev"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: ./main_cli

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: google-github-actions/release-please-action@v3
          id: release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release-type: python
            path: main_cli
            monorepo-tags: true
            package-name: main_cli
            tag-separator: '@'
            prerelease: >-
              ${{ github.event.inputs.stage == '' || github.event.inputs.stage != 'prod' }}
